/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AppImport } from './routes/_app'
import { Route as IndexImport } from './routes/index'
import { Route as ServerDownIndexImport } from './routes/server-down/index'
import { Route as LoginIndexImport } from './routes/login/index'
import { Route as AppHomeImport } from './routes/_app/home'
import { Route as AppHomeIndexImport } from './routes/_app/home/index'
import { Route as AppHomeRoomIdIndexImport } from './routes/_app/home/$roomId/index'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AppRoute = AppImport.update({
  id: '/_app',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const ServerDownIndexRoute = ServerDownIndexImport.update({
  id: '/server-down/',
  path: '/server-down/',
  getParentRoute: () => rootRoute,
} as any)

const LoginIndexRoute = LoginIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LoginRoute,
} as any)

const AppHomeRoute = AppHomeImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)

const AppHomeIndexRoute = AppHomeIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppHomeRoute,
} as any)

const AppHomeRoomIdIndexRoute = AppHomeRoomIdIndexImport.update({
  id: '/$roomId/',
  path: '/$roomId/',
  getParentRoute: () => AppHomeRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/solid-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AppImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeImport
      parentRoute: typeof AppImport
    }
    '/login/': {
      id: '/login/'
      path: '/'
      fullPath: '/login/'
      preLoaderRoute: typeof LoginIndexImport
      parentRoute: typeof LoginImport
    }
    '/server-down/': {
      id: '/server-down/'
      path: '/server-down'
      fullPath: '/server-down'
      preLoaderRoute: typeof ServerDownIndexImport
      parentRoute: typeof rootRoute
    }
    '/_app/home/': {
      id: '/_app/home/'
      path: '/'
      fullPath: '/home/'
      preLoaderRoute: typeof AppHomeIndexImport
      parentRoute: typeof AppHomeImport
    }
    '/_app/home/$roomId/': {
      id: '/_app/home/$roomId/'
      path: '/$roomId'
      fullPath: '/home/$roomId'
      preLoaderRoute: typeof AppHomeRoomIdIndexImport
      parentRoute: typeof AppHomeImport
    }
  }
}

// Create and export the route tree

interface AppHomeRouteChildren {
  AppHomeIndexRoute: typeof AppHomeIndexRoute
  AppHomeRoomIdIndexRoute: typeof AppHomeRoomIdIndexRoute
}

const AppHomeRouteChildren: AppHomeRouteChildren = {
  AppHomeIndexRoute: AppHomeIndexRoute,
  AppHomeRoomIdIndexRoute: AppHomeRoomIdIndexRoute,
}

const AppHomeRouteWithChildren =
  AppHomeRoute._addFileChildren(AppHomeRouteChildren)

interface AppRouteChildren {
  AppHomeRoute: typeof AppHomeRouteWithChildren
}

const AppRouteChildren: AppRouteChildren = {
  AppHomeRoute: AppHomeRouteWithChildren,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface LoginRouteChildren {
  LoginIndexRoute: typeof LoginIndexRoute
}

const LoginRouteChildren: LoginRouteChildren = {
  LoginIndexRoute: LoginIndexRoute,
}

const LoginRouteWithChildren = LoginRoute._addFileChildren(LoginRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/home': typeof AppHomeRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/server-down': typeof ServerDownIndexRoute
  '/home/': typeof AppHomeIndexRoute
  '/home/$roomId': typeof AppHomeRoomIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AppRouteWithChildren
  '/login': typeof LoginIndexRoute
  '/server-down': typeof ServerDownIndexRoute
  '/home': typeof AppHomeIndexRoute
  '/home/$roomId': typeof AppHomeRoomIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRouteWithChildren
  '/_app/home': typeof AppHomeRouteWithChildren
  '/login/': typeof LoginIndexRoute
  '/server-down/': typeof ServerDownIndexRoute
  '/_app/home/': typeof AppHomeIndexRoute
  '/_app/home/$roomId/': typeof AppHomeRoomIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/home'
    | '/login/'
    | '/server-down'
    | '/home/'
    | '/home/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '' | '/login' | '/server-down' | '/home' | '/home/$roomId'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/_app/home'
    | '/login/'
    | '/server-down/'
    | '/_app/home/'
    | '/_app/home/$roomId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRouteWithChildren
  ServerDownIndexRoute: typeof ServerDownIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRouteWithChildren,
  ServerDownIndexRoute: ServerDownIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_app",
        "/login",
        "/server-down/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_app": {
      "filePath": "_app.tsx",
      "children": [
        "/_app/home"
      ]
    },
    "/login": {
      "filePath": "login.tsx",
      "children": [
        "/login/"
      ]
    },
    "/_app/home": {
      "filePath": "_app/home.tsx",
      "parent": "/_app",
      "children": [
        "/_app/home/",
        "/_app/home/$roomId/"
      ]
    },
    "/login/": {
      "filePath": "login/index.tsx",
      "parent": "/login"
    },
    "/server-down/": {
      "filePath": "server-down/index.tsx"
    },
    "/_app/home/": {
      "filePath": "_app/home/index.tsx",
      "parent": "/_app/home"
    },
    "/_app/home/$roomId/": {
      "filePath": "_app/home/$roomId/index.tsx",
      "parent": "/_app/home"
    }
  }
}
ROUTE_MANIFEST_END */
